events {}

http {
    gzip on;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            expires 3d;
        }

        location /api {
            proxy_pass http://host.docker.internal:3000;
        }
    }
}
